export const featured = {
  id: 1,
  title: "Hot Fish Dog",
  description: "Food Categories",
  restaurants: [
    {
      id: 22,
      name: "mumys coffe",
      location: "kigali Rwanda",
      description: "hot meat and Pizza",
      image: require(`../assets/images/dishes/haha.jpeg`),
      lang: 38.2145602,
      lat: -85.5324269,
      address: "435 second street",
      starts: 4,
      reviews: "4.4k",
      category: "Fast Food",
      dishes: [
        {
          id: 1,
          name: "pizza",
          description: "cheezy garlic pizza",
          proce: 10,
          image: require(`../assets/images/dishes/images.jpeg`),
        },
        {
          id: 2,
          name: "pizza",
          description: "cheezy garlic pizza",
          proce: 10,
          image: require(`../assets/images/dishes/images.jpeg`),
        },
        {
          id: 3,
          name: "pizza",
          description: "cheezy garlic pizza",
          proce: 10,
          image: require(`../assets/images/dishes/images.jpeg`),
        },
        {
          id: 4,
          name: "pizza",
          description: "cheezy garlic pizza",
          proce: 10,
          image: require(`../assets/images/dishes/images.jpeg`),
        },
        {
          id: 5,
          name: "pizza",
          description: "cheezy garlic pizza",
          proce: 10,
          image: require(`../assets/images/dishes/images.jpeg`),
        },
        {
          id: 6,
          name: "pizza",
          description: "cheezy garlic pizza",
          proce: 10,
          image: require(`../assets/images/dishes/images.jpeg`),
        },
      ],
    },
    {
      id: 32,
      name: "mumys coffe",
      location: "kigali Rwanda",
      description: "hot meat and Pizza",
      image: require(`../assets/images/dishes/ibirabyo.jpeg`),
      lang: 38.2145602,
      lat: -85.5324269,
      address: "435 second street",
      starts: 4,
      reviews: "4.4k",
      category: "Fast Food",
      dishes: [
        {
          id: 1,
          name: "pizza",
          description: "cheezy garlic pizza",
          proce: 10,
          image: require(`../assets/images/dishes/images.jpeg`),
        },
        {
          id: 32,
          name: "pizza",
          description: "cheezy garlic pizza",
          proce: 10,
          image: require(`../assets/images/dishes/images.jpeg`),
        },
        {
          id: 33,
          name: "pizza",
          description: "cheezy garlic pizza",
          proce: 10,
          image: require(`../assets/images/dishes/images.jpeg`),
        },
        {
          id: 42,
          name: "pizza",
          description: "cheezy garlic pizza",
          proce: 10,
          image: require(`../assets/images/dishes/images.jpeg`),
        },
        {
          id: 35,
          name: "pizza",
          description: "cheezy garlic pizza",
          proce: 10,
          image: require(`../assets/images/dishes/images.jpeg`),
        },
        {
          id: 326,
          name: "pizza",
          description: "cheezy garlic pizza",
          proce: 10,
          image: require(`../assets/images/dishes/images.jpeg`),
        },
      ],
    },
    {
      id: 32,
      name: "mumys coffe",
      location: "kigali Rwanda",
      description: "hot meat and Pizza",
      image: require(`../assets/images/dishes/bugger.jpeg`),
      lang: 38.2145602,
      lat: -85.5324269,
      address: "435 second street",
      starts: 4,
      reviews: "4.4k",
      category: "Fast Food",
      dishes: [
        {
          id: 1,
          name: "pizza",
          description: "cheezy garlic pizza",
          proce: 10,
          image: require(`../assets/images/dishes/images.jpeg`),
        },
        {
          id: 32,
          name: "pizza",
          description: "cheezy garlic pizza",
          proce: 10,
          image: require(`../assets/images/dishes/images.jpeg`),
        },
        {
          id: 33,
          name: "pizza",
          description: "cheezy garlic pizza",
          proce: 10,
          image: require(`../assets/images/dishes/images.jpeg`),
        },
        {
          id: 42,
          name: "pizza",
          description: "cheezy garlic pizza",
          proce: 10,
          image: require(`../assets/images/dishes/images.jpeg`),
        },
        {
          id: 35,
          name: "pizza",
          description: "cheezy garlic pizza",
          proce: 10,
          image: require(`../assets/images/dishes/images.jpeg`),
        },
        {
          id: 326,
          name: "pizza",
          description: "cheezy garlic pizza",
          proce: 10,
          image: require(`../assets/images/dishes/images.jpeg`),
        },
      ],
    },
    {
      id: 32,
      name: "mumys coffe",
      location: "kigali Rwanda",
      description: "hot meat and Pizza",
      image: require(`../assets/images/dishes/igi.jpeg`),
      lang: 38.2145602,
      lat: -85.5324269,
      address: "435 second street",
      starts: 4,
      reviews: "4.4k",
      category: "Fast Food",
      dishes: [
        {
          id: 1,
          name: "pizza",
          description: "cheezy garlic pizza",
          proce: 10,
          image: require(`../assets/images/dishes/images.jpeg`),
        },
        {
          id: 32,
          name: "pizza",
          description: "cheezy garlic pizza",
          proce: 10,
          image: require(`../assets/images/dishes/images.jpeg`),
        },
        {
          id: 33,
          name: "pizza",
          description: "cheezy garlic pizza",
          proce: 10,
          image: require(`../assets/images/dishes/images.jpeg`),
        },
        {
          id: 42,
          name: "pizza",
          description: "cheezy garlic pizza",
          proce: 10,
          image: require(`../assets/images/dishes/images.jpeg`),
        },
        {
          id: 35,
          name: "pizza",
          description: "cheezy garlic pizza",
          proce: 10,
          image: require(`../assets/images/dishes/images.jpeg`),
        },
        {
          id: 326,
          name: "pizza",
          description: "cheezy garlic pizza",
          proce: 10,
          image: require(`../assets/images/dishes/images.jpeg`),
        },
      ],
    },
    {
      id: 32,
      name: "mumys coffe",
      location: "kigali Rwanda",
      description: "hot meat and Pizza",
      image: require(`../assets/images/dishes/images.jpeg`),
      lang: 38.2145602,
      lat: -85.5324269,
      address: "435 second street",
      starts: 4,
      reviews: "4.4k",
      category: "Fast Food",
      dishes: [
        {
          id: 1,
          name: "pizza",
          description: "cheezy garlic pizza",
          proce: 10,
          image: require(`../assets/images/dishes/images.jpeg`),
        },
        {
          id: 32,
          name: "pizza",
          description: "cheezy garlic pizza",
          proce: 10,
          image: require(`../assets/images/dishes/images.jpeg`),
        },
        {
          id: 33,
          name: "pizza",
          description: "cheezy garlic pizza",
          proce: 10,
          image: require(`../assets/images/dishes/images.jpeg`),
        },
        {
          id: 42,
          name: "pizza",
          description: "cheezy garlic pizza",
          proce: 10,
          image: require(`../assets/images/dishes/images.jpeg`),
        },
        {
          id: 35,
          name: "pizza",
          description: "cheezy garlic pizza",
          proce: 10,
          image: require(`../assets/images/dishes/images.jpeg`),
        },
        {
          id: 326,
          name: "pizza",
          description: "cheezy garlic pizza",
          proce: 10,
          image: require(`../assets/images/dishes/images.jpeg`),
        },
      ],
    },
  ],
};

export const Categolie = [
  {
    id: 1,
    name: "Fish",
    image: require(`../assets/images/categories/fish.png`),
  },
  {
    id: 2,
    name: "Fanta",
    image: require(`../assets/images/categories/fanta.png`),
  },
  {
    id: 3,
    name: "Food",
    image: require(`../assets/images/categories/food.png`),
  },
  {
    id: 4,
    name: "PizzaSlice",
    image: require(`../assets/images/categories/pizzaslice.png`),
  },
  {
    id: 5,
    name: "Pizza",
    image: require(`../assets/images/categories/pizza.png`),
  },
  {
    id: 6,
    name: "Drinks",
    image: require(`../assets/images/categories/drinks.png`),
  },
];
